# Name of workflow
name: Development workflow

# When workflow is triggered
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

# Jobs to carry out
jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    #   - name: Install dependencies
    #     run: npm install
        
    #   - name: Build app
    #     run: npm run build
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean install dependencies
      run: npm ci
    - name: Building App
      run: npm run build --if-present
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        
      - name: Run unit tests
        run: npm run test --if-present

  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    needs:
      - build
      - test

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
